CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "Users" (
  "id" UUID DEFAULT public.uuid_generate_v4(),
  "userId" SERIAL PRIMARY KEY UNIQUE,
  "username" VARCHAR(32) NOT NULL UNIQUE,
  "email" VARCHAR(64),
  "firstname" VARCHAR(40) NOT NULL,
  "lastname" VARCHAR(40) NOT NULL,
  "password" text NOT NULL,
  "verified" BOOLEAN DEFAULT 'false',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "users_data" FOREIGN KEY ("userId") REFERENCES "RoadTrips", "Interests" ON UPDATE CASCADE ON DELETE CASCADE;
);

ALTER TABLE "Users" ADD FOREIGN KEY ("userId") REFERENCES "Interests" ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Users" ADD FOREIGN KEY ("userId") REFERENCES "RoadTrips" ON DELETE CASCADE ON UPDATE CASCADE;